import { Usuario } from "@prisma/client";

export type CreateUsuarioDto = Pick<
    Usuario,
    | 'nomeCompleto'
    | 'cpf'
    | 'senhaHash'
    | 'tokenResetarSenha'
    | 'validadeTokenResetadaSenha'
    | 'email'
    | 'status'
    | 'administrador'
    | 'coordenador'
    | 'secretaria'
    | 'professor'
    | 'perfil'
    | 'siape'
    | 'dataIngresso'
    | 'endereco'
    | 'telCelular'
    | 'telResidencial'
    | 'unidade'
    | 'turno'
    | 'idLattes'
    | 'formacao'
    | 'formacaoIngles'
    | 'resumo'
    | 'resumoIngles'
    | 'ultimaAtualizacao'

>

export type UpdateUsuarioDto = Pick<
    Usuario,
    | 'nomeCompleto'
    | 'cpf'
    | 'senhaHash'
    | 'tokenResetarSenha'
    | 'validadeTokenResetadaSenha'
    | 'email'
    | 'status'
    | 'administrador'
    | 'coordenador'
    | 'secretaria'
    | 'professor'
    | 'perfil'
    | 'siape'
    | 'dataIngresso'
    | 'endereco'
    | 'telCelular'
    | 'telResidencial'
    | 'unidade'
    | 'turno'
    | 'idLattes'
    | 'formacao'
    | 'formacaoIngles'
    | 'resumo'
    | 'resumoIngles'
    | 'ultimaAtualizacao'
>