version: '3.8'
services:
  db:
    image: mysql:8
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "${MYSQL_PORT}:3306"
  
  sysicomp:
    build: .
    env_file:
      - .env
    ports: 
      - "${PORT}:3000"
    working_dir: /app
    volumes: 
      - .:/app
      - /app/node_modules
    depends_on: 
      - db

#Docker Networks
networks:
  sysicomp-network:
    driver: bridge
