services:
  db:
    container_name: db_sysicomp-dev
    image: mysql:8.4
    restart: no
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - '${MYSQL_PORT:-3306}:3306'
    volumes:
      - db-sysicomp-dev:/var/lib/mysql
    networks:
      - sysicomp-network-dev

  redis:
    container_name: redis_sysicomp-dev
    image: redis:alpine
    restart: unless-stopped
    networks:
      - sysicomp-network-dev
    ports:
      - '${REDIS_PORT:-6379}:6379'

  phpmyadmin:
    container_name: phpmyadmin_sysicomp-dev
    image: phpmyadmin/phpmyadmin:latest
    restart: no
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - '8080:80'
    depends_on:
      - db
    networks:
      - sysicomp-network-dev

  sysicomp:
    container_name: sysicomp-dev
    build:
      context: .
      dockerfile: Dockerfile.devlopment
    command: 'npm run start:syscomp'
    restart: no
    ports:
      - '${PORT:-3000}:${PORT:-3000}'
    working_dir: /app
    volumes:
      - .:/app:delegated
      - /app/node_modules
      - ./logs:/app/logs
      - ./uploads:/app/uploads
    depends_on:
      - db
      - gotenberg
      - redis
    env_file:
      - .env
    networks:
      - sysicomp-network-dev

  selecao_ppgi:
    container_name: selecao_ppgi-dev
    build:
      context: .
      dockerfile: Dockerfile.devlopment
    command: 'npm run start:selecao'
    restart: "no"
    ports:
      - '${PORT_SELECAO:-4000}:${PORT_SELECAO:-4000}'
    working_dir: /app
    volumes:
      - .:/app:delegated
      - /app/node_modules
      - ./logs:/app/logs
      - ./uploads:/app/uploads
    depends_on:
      - db
      - gotenberg
      - redis
    env_file:
      - .env
    networks:
      - sysicomp-network-dev

  numeros_icomp:
    container_name: numeros_icomp-dev
    build:
      context: .
      dockerfile: Dockerfile.devlopment
    command: 'npm run start:numeros'
    restart: no
    ports:
      - '${PORT_NUMEROS_ICOMP:-3003}:${PORT_NUMEROS_ICOMP:-3003}'
    working_dir: /app
    volumes:
      - .:/app:delegated
      - /app/node_modules
      - ./logs:/app/logs
      - ./uploads:/app/uploads
    depends_on:
      - db
      - gotenberg
      - redis
    env_file:
      - .env
    networks:
      - sysicomp-network-dev

  gotenberg:
    container_name: gotenberg-dev
    image: gotenberg/gotenberg:8
    restart: no
    mem_limit: 256m
    ports:
      - '${PORT_GOTENBERG:-3002}:3000'  # Expondo porta padrão 3000 do Gotenberg para localhost na 3001
    networks:
      - sysicomp-network-dev

# Redes isoladas para os serviços
networks:
  sysicomp-network-dev:
    driver: bridge

# Persistência do banco de dados
volumes:
  db-sysicomp-dev: