services:
  db:
    container_name: db_sysicomp
    image: mysql:8.4
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - '${MYSQL_PORT:-3306}:3306'
    volumes:
      - db_sysicomp:/var/lib/mysql
    networks:
      - sysicomp-network

  redis:
    container_name: redis_sysicomp
    image: redis:alpine
    restart: unless-stopped
    mem_limit: 512m
    command: redis-server --maxmemory 450mb --maxmemory-policy allkeys-lru
    networks:
      - sysicomp-network

  sysicomp:
    container_name: sysicomp
    mem_limit: 512m
    build:
      context: .
    command: 'node build/server.js'
    restart: unless-stopped
    ports:
      - '${PORT:-3000}:${PORT:-3000}'
    volumes:
      - ./logs:/app/logs
      - ./uploads:/app/uploads
      - ./temp:/app/temp
    depends_on:
      - db
      - gotenberg
      - redis
    env_file:
      - .env
    networks:
      - sysicomp-network
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

  selecao_ppgi:
    container_name: selecao_ppgi
    mem_limit: 4096m
    build:
      context: .
    command: 'node build/serverSelecao.js'
    restart: unless-stopped
    ports:
      - '${PORT_SELECAO:-4000}:${PORT_SELECAO:-4000}'
    volumes:
      - ./logs:/app/logs
      - ./uploads:/app/uploads
      - ./temp:/app/temp

    depends_on:
      - db
      - gotenberg
      - redis
    env_file:
      - .env
    networks:
      - sysicomp-network
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

  numeros_icomp:
    container_name: numeros_icomp
    mem_limit: 4096m
    build:
      context: .
    command: 'node build/app/serverNumerosIcomp.js'
    restart: unless-stopped
    ports:
      - '${PORT_NUMEROS_ICOMP:-4001}:${PORT_NUMEROS_ICOMP:-4001}'
    volumes:
      - ./logs:/app/logs
      - ./uploads:/app/uploads
      - ./temp:/app/temp
    depends_on:
      - db
      - gotenberg
      - redis
    env_file:
      - .env
    networks:
      - sysicomp-network
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

  gotenberg:
    container_name: gotenberg
    image: gotenberg/gotenberg:8
    restart: unless-stopped
    mem_limit: 2055m
    memswap_limit: 3079m
    ports:
      - '${PORT_GOTENBERG:-3002}:3000'
    networks:
      - sysicomp-network


networks:
  sysicomp-network:
    driver: bridge

volumes:
  db_sysicomp:
  portainer_data: