import { Candidato } from '@prisma/client';

export type CreateCandidateDto = Pick<
  Candidato,
  | 'email'
  | 'senhaHash'
  | 'validarTokenResetada'
  | 'tokenResetSenha'
  | 'anoEgressoGraduacao'
  | 'bolsista'
  | 'bairro'
  | 'cep'
  | 'cidade'
  | 'comoSoube'
  | 'condicao'
  | 'condicaoTipo'
  | 'cotista'
  | 'cotistaTipo'
  | 'uf'
  | 'cursoPos'
  | 'cursoDesejado'
  | 'anoEgressoPos'
  | 'cartaDoOrientador'
  | 'cursoGraduacao'
  | 'curriculum'
  | 'dataNascimento'
  | 'endereco'
  | 'instituicaoGraduacao'
  | 'idEdital'
  | 'idLinhaPesquisa'
  | 'instituicaoPos'
  | 'motivos'
  | 'nacionalidade'
  | 'nome'
  | 'nomeSocial'
  | 'regime'
  | 'sexo'
  | 'telefone'
  | 'telefoneSecundario'
  | 'nomeOrientador'
  | 'posicaoEdital'
  | 'propostaDeTrabalho'
  | 'tipoPos'
  | 'tituloProposta'
>;

export type UpdateCandidateDto = Pick<
  Candidato,
  | 'email'
  | 'senhaHash'
  | 'validarTokenResetada'
  | 'tokenResetSenha'
  | 'anoEgressoGraduacao'
  | 'bolsista'
  | 'bairro'
  | 'cep'
  | 'cidade'
  | 'comoSoube'
  | 'condicao'
  | 'condicaoTipo'
  | 'cotista'
  | 'cotistaTipo'
  | 'uf'
  | 'cursoPos'
  | 'cursoDesejado'
  | 'anoEgressoPos'
  | 'cartaDoOrientador'
  | 'cursoGraduacao'
  | 'curriculum'
  | 'dataNascimento'
  | 'endereco'
  | 'instituicaoGraduacao'
  | 'idEdital'
  | 'idLinhaPesquisa'
  | 'instituicaoPos'
  | 'motivos'
  | 'nacionalidade'
  | 'nome'
  | 'nomeSocial'
  | 'regime'
  | 'sexo'
  | 'telefone'
  | 'telefoneSecundario'
  | 'nomeOrientador'
  | 'posicaoEdital'
  | 'propostaDeTrabalho'
  | 'tipoPos'
  | 'tituloProposta'
>;

export type CandidateSemSenha = Omit<Candidato, 'passwordHash'>;
