-- AlterTable
ALTER TABLE `LattesFormacaoAcademicaTitulacao` MODIFY `tipoFormacao` ENUM('GRADUACAO', 'ESPECIALIZACAO', 'MESTRADO', 'MESTRADO_PROFISSIONALIZANTE', 'DOUTORADO', 'POS_DOUTORADO', 'LIVRE_DOCENCIA', 'RESIDENCIA_MEDICA', 'CURSO_TECNICO_PROFISSIONALIZANTE', 'APERFEICOAMENTO', 'ENSINO_MEDIO', 'ENSINO_FUNDAMENTAL', 'ENSINO_MEDIO_SEGUNDO_GRAU') NOT NULL;

-- AlterTable
ALTER TABLE `LattesProfessor` MODIFY `nomeEmCitacoesProfessor` VARCHAR(600) NULL;
